site_name: UNB - Engenharia de Software

nav:
  - Apresentação Prezi: index.md
  - FSO:
    - Visão Geral de um computador: fundamentos_de_SO/visao_geral.md
    - Classificações dos SO: fundamentos_de_SO/classificacoes_SO.md
    - Estrutura dos Sistema Operacional: fundamentos_de_SO/estrutura_kernel.md
    - Processos: processos/processos.md
  - Compiladores:
    - Analisador Sintático: compiladores/sintantico.md

theme:
  name: material
  icon:
    repo: fontawesome/brands/github

  font:
    text: Ubuntu

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.prune
    - navigation.top
    - navigation.footer
    - navigations.indexes
    - content.code.copy
    - toc.integrate
    - search.suggest
    - search.highlight

  nav_style: dark
  language: pt
  repo: fontawesome/brands/github

  palette:
    - scheme: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Alternar para modo escuro
      primary: blue
      accent: light blue

    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Alternar para modo claro
      primary: black
      accent: light blue

  markdown_extensions:
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
      pygments_lang_class: true
    - pymdownx.keys
    - pymdownx.smartsymbols
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.betterem
    - pymdownx.inlinehilite
    - admonition
    - footnotes
    - pymdownx.details
    - pymdownx.superfences
    - attr_list
    - pymdownx.snippets
